# 4. Pandas - Intro Data Structures (1)

## What is pandas?

Pandas is a 'package' that contains data structures and data manipulation tools designed to make data cleaning and analysis fast and easy in Python.

In this notebook the most basic functionalities will be covered.

### How do I use it?

In [1]:
# We import pandas as "pd". This is not required, but it's standard. 
import pandas as pd

### Pandas Data Structures

There are two main data structures on pandas:
- **Series** - A One-dimensional array of data of the same type. More documentation on Series is available on: [Pandas Series Documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)


- **Dataframes** - Tabular structure that may be seen as a container of series (that may have different types). Be aware that is also possible to have one-dimensional array of data as a DataFrame. More documentation on Dataframes is available on: [Pandas Dataframes Documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)


## Series

Creating a series in pandas is really easy. We will start by creating a series of numbers and print it to see how it look likes.

In [2]:
s1 = pd.Series([4, 7, 2, 10, 3, 8])
s1

0     4
1     7
2     2
3    10
4     3
5     8
dtype: int64

The defined values have the given index: from 0 to the length of the data minus 1 -> 5. Notice as well that the series has one and only one type of data, in this case `int64`. Pandas is quite clever inferring what kind of data is passed to it. Additonally it's possible to observe that the order of the data has been maintained.

Let's see what will happen if we pass it some floats, instead of ints: 

In [3]:
s2 = pd.Series([4, -7.5, 2, 10, 3.2, 8])
s2

0     4.0
1    -7.5
2     2.0
3    10.0
4     3.2
5     8.0
dtype: float64

Ok, so now it's a `float64` series. 

Next up, the same, but this time with some strings: 

In [4]:
s3 = pd.Series(["Google", "Apple", "Microsoft", "Facebook"])
s3

0       Google
1        Apple
2    Microsoft
3     Facebook
dtype: object

Ok, this time it was considered `object`. Objects are types of data that can point to different types of data as we may see in the example below.

Fair question: what happens if you pass it a mix of stuff? 

In [5]:
s4 = pd.Series([1.2, 5.3, "it\'s a string", -4])
s4

0              1.2
1              5.3
2    it's a string
3               -4
dtype: object

Well, when everything is mixed, it makes it an object! 

Series have a class attribute that shows us their data type. It's called **dtype** and can be used like this:

In [6]:
s1.dtype

dtype('int64')

In [7]:
s4.dtype

dtype('O')

# Indexing 

In [8]:
s4[1]

5.3

How do you get the first element of a series?

In [9]:
### Your code here


Even though by default the index is _0, 1, 2, 3..._ it is often useful to set a different index.

In [10]:
s5 = pd.Series(data=["Harry", "Jone", "Julia", "Sara"], 
               index=["Google", "Apple", "Microsoft", "Facebook"])
s5

Google       Harry
Apple         Jone
Microsoft    Julia
Facebook      Sara
dtype: object

In [11]:
s5["Apple"]

'Jone'

We can also get all the values (still a bit like a dictionary): 

In [12]:
s5.values

array(['Harry', 'Jone', 'Julia', 'Sara'], dtype=object)

Or the indexes (like the `.keys()` of the dictionary) 

In [13]:
s5.index

Index(['Google', 'Apple', 'Microsoft', 'Facebook'], dtype='object')

Speaking of dictionaries, can I make a Pandas Series from a dictionary? 

In [14]:
d = {"Google": "Harry", "Apple": "Jone", "Microsoft": "Julia", "Facebook": "Sara"}
s6 = pd.Series(d)
s6

Google       Harry
Apple         Jone
Microsoft    Julia
Facebook      Sara
dtype: object

Yes!! The Series class will automatically use the keys of the dictionary as indexes of the series and its correponding data as the data of the series as well. The interesting part of using this is that we now are able to have some functionalities that we usually don't have in dictionaries.

In [15]:
try:
    d[-1:]
except:
    print("TypeError")

TypeError


In [16]:
s6[-1:]

Facebook    Sara
dtype: object

---

## DataFrames

As mentioned previously, a dataframe is a tabular structure (think "Excel sheet"). This will become clear with the following examples.

Let's create our first DataFrame: 

In [17]:
df1 = pd.DataFrame([[1,   2,   3,    5], 
                    [14.3, 16.7, 18.1, 12.2], 
                    ["a", "b", "c", "d"] ],
                    columns=["col_1", "col_2", "col_3", "col_4"],  # <-- The column names
                    index=["row_1", "row_2", "row_3"]) # <-- The row names

In [18]:
df1

col_1 col_2 col_3 col_4
row_1     1     2     3     5
row_2  14.3  16.7  18.1  12.2
row_3     a     b     c     d

So far we've creatad a DataFrame from lists, like so: 

In [19]:
company = ["Google", "Apple", "Microsoft", "Facebook"]
founder_name = ["Page", "Jobs", "Gates", "Zuckerberg"]
foundation_year = [1998, 1976, 1975, 2004]

df2 = pd.DataFrame( [company, founder_name, foundation_year])

In [20]:
df2

0      1          2           3
0  Google  Apple  Microsoft    Facebook
1    Page   Jobs      Gates  Zuckerberg
2    1998   1976       1975        2004

We can make a dictionary with the lists as values, where the keys will be the column names. Let's create the dictionary first, using the lists we have defined above: 

In [21]:
companies_dictionary = {
    'company': ["Google", "Apple", "Microsoft", "Facebook"],
    'founder_name': ["Page", "Jobs", "Gates", "Zuckerberg"],
    'foundation_year': [1998, 1976, 1975, 2004]
}

Now we can simply pass this dictionary to a Pandas DataFrame: 

In [22]:
df3 = pd.DataFrame(companies_dictionary)

In [23]:
df3

company founder_name  foundation_year
0     Google         Page             1998
1      Apple         Jobs             1976
2  Microsoft        Gates             1975
3   Facebook   Zuckerberg             2004

What is the difference in the presentation of this data?

Let's make some Series, using the company name as index: 

In [24]:
series_of_founder_name = pd.Series(data=founder_name, # <-- data 
                                    index=company)      # <-- index 

In [25]:
series_of_founder_name

Google             Page
Apple              Jobs
Microsoft         Gates
Facebook     Zuckerberg
dtype: object

In [26]:
series_of_foundation_year = pd.Series(data=foundation_year, # <-- different data
                                    index=company)        # <-- same index 

In [27]:
series_of_foundation_year

Google       1998
Apple        1976
Microsoft    1975
Facebook     2004
dtype: int64

Now with these two Series we can create a DataFrame! Pandas will notice that they have the same index, and will give the DataFrame that index: 

In [28]:
df4 = pd.DataFrame({'founder_name': series_of_founder_name,  
                    'foundation_year': series_of_foundation_year})

In [29]:
df4

founder_name  foundation_year
Google            Page             1998
Apple             Jobs             1976
Microsoft        Gates             1975
Facebook    Zuckerberg             2004

By passing series (in this case sharing the index) as values of a dictionary, the model is able to use the key value as column name and the index as the row name. The column and index(row) are also acessible, as will be shown below.

Get index, with `.index`: 

In [30]:
df4.index

Index(['Google', 'Apple', 'Microsoft', 'Facebook'], dtype='object')

Get the columns, with `.columns`: 

In [31]:
df4.columns

Index(['founder_name', 'foundation_year'], dtype='object')

We can also use `dtypes` to know the type of each series of the dataframe:

In [32]:
df4.dtypes

founder_name       object
foundation_year     int64
dtype: object

### Visualizing the DataFrame or part of it

To visualize a DataFrame, using a jupyter-notebook, printing will display it (as seen previously).

In [33]:
df4

founder_name  foundation_year
Google            Page             1998
Apple             Jobs             1976
Microsoft        Gates             1975
Facebook    Zuckerberg             2004

In the case that the dataframe has a lot of entries, it will be only partially displayed. Nonetheless, it might still be too much information being displayed at once. The methods `.head` and `.tail` print the n top and bottom, respectively, lines of the dataframe.

In [34]:
df4.head(2)

founder_name  foundation_year
Google         Page             1998
Apple          Jobs             1976

In [35]:
df4.tail(2)

founder_name  foundation_year
Microsoft        Gates             1975
Facebook    Zuckerberg             2004

### Getting the relevant info

With pandas' [info](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.info.html) it possible to obtain:
- How many entries it has.
- The total number of columns.
- The title of each column.
- The number of entries that in fact exists in each column. Does not consider misssing values.
- The type of data of the entries of a given column.

In [36]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Google to Facebook
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   founder_name     4 non-null      object
 1   foundation_year  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes


For the **NUMERICAL** variables it's also possible to print some more information using [describe](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html), namely:

- The number of rows for each of those columns.
- The mean value.
- The standard deviation.
- The minimum and maximum value.
- The median, the 25th and 75th percentile.

In [37]:
df4.describe() # doesn't make a lot sense for the variable year though

foundation_year
count         4.000000
mean       1988.250000
std          14.930394
min        1975.000000
25%        1975.750000
50%        1987.000000
75%        1999.500000
max        2004.000000

Finally, [shape](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.shape.html) returns a tuple with the dimensions of the dataframe (nr_rows, nr_columns).

In [38]:
df4.shape

(4, 2)

## Reading from the disk

Pandas framework has implemented functions that allow us to create dataframes form different types of data:

- CSV
- JSON
- HTML
- ... and [many more](https://pandas.pydata.org/pandas-docs/stable/io.html)

All of this is possible by using the read_*dataFormat*. With it is possible to create a dataframe and apply all the previously shown techniques. 

For instance, using the 2010 census profile and housing characteristics of the city of Los Angeles ([source](https://catalog.data.gov/dataset/2010-census-populations-by-zip-code)):

In [39]:
data = pd.read_csv("Data/2010_Census_Populations_by_Zip_Code.csv")

How does the data look like? Use methods mentioned above.

In [40]:
### Your code here
data.describe()

Zip Code  Total Population  Median Age   Total Males  \
count    319.000000        319.000000  319.000000    319.000000   
mean   91000.673981      33241.341693   36.527586  16391.564263   
std      908.360203      21644.417455    8.692999  10747.495566   
min    90001.000000          0.000000    0.000000      0.000000   
25%    90243.500000      19318.500000   32.400000   9763.500000   
50%    90807.000000      31481.000000   37.100000  15283.000000   
75%    91417.000000      44978.000000   41.000000  22219.500000   
max    93591.000000     105549.000000   74.000000  52794.000000   

       Total Females  Total Households  Average Household Size  
count     319.000000        319.000000              319.000000  
mean    16849.777429      10964.570533                2.828119  
std     10934.986468       6270.646400                0.835658  
min         0.000000          0.000000                0.000000  
25%      9633.500000       6765.500000                2.435000  
50%     16202.000000      10968.000000                2.830000  
75%     22690.500000      14889.500000                3.320000  
max     53185.000000      31087.000000                4.670000

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Zip Code                319 non-null    int64  
 1   Total Population        319 non-null    int64  
 2   Median Age              319 non-null    float64
 3   Total Males             319 non-null    int64  
 4   Total Females           319 non-null    int64  
 5   Total Households        319 non-null    int64  
 6   Average Household Size  319 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 17.6 KB


## Writing to the disk

Besides reading from the disk, Pandas allows us to also write and save our dataframe after we performed some transformations to the data.

The same way we can read data from various data types, we can also write data to various data types (CSV, JSON, HTML, ...)

All of this is possible by using the to_*dataFormat*, giving as an argument the path where you want to save the file:

In [42]:
data.to_csv("Data/test_csv.csv")

---

# Exercises ad 4

### Create a pandas Series with some countries, capital and population

In [52]:
# Create a pandas Series from the list ['Denmark', 'Finland', 'Iceland', 'Norway', 'Greenland', 'Faroe Islands']
countries = pd.Series(data=['Denmark', 'Finland', 'Iceland', 'Norway', 'Greenland', 'Faroe Islands']) 

# Create a pandas Series from the list ['Copenhagen', 'Helsinki', 'Reykjavík', 'Oslo', 'Nuuk', 'Tórshavn']
capitals = pd.Series(data=['Copenhagen', 'Helsinki', 'Reykjavík', 'Oslo', 'Nuuk', 'Tórshavn'])

# Create a pandas Series from the list [5724456, 5498211, 335878, 5265158,56483,49188]
pop = pd.Series(data=[5724456, 5498211, 335878, 5265158,56483,49188])

### Create a pandas DataFrame

In [53]:
### your code here
nordic_countries = pd.DataFrame({'countries':countries,
                                 'capitals':capitals,
                                 'population':pop})

In [54]:
nordic_countries.head()

countries    capitals  population
0    Denmark  Copenhagen     5724456
1    Finland    Helsinki     5498211
2    Iceland   Reykjavík      335878
3     Norway        Oslo     5265158
4  Greenland        Nuuk       56483

### Load the file _iris.csv_

In [43]:
iris = pd.read_csv('Data/iris.csv') ### your code here

### Get info about the DataFrame

In [56]:
### your code here
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


### Print the top 10 entries

In [57]:
### your code here
iris.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

### Print the bottom 10 entries

In [58]:
### your code here
iris.tail(10)

sepal.length  sepal.width  petal.length  petal.width    variety
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

### Get the shape of the DataFrame

In [59]:
### your code here
iris.shape

(150, 5)

### Get more information about the numerical features

In [60]:
### your code here
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

---

# 5. Pandas - Data Processing (2)

## Indexing 

An **index** is a labeling that allows us to locate data points across a Dataframe or series more easily. 

Both rows and columns have these labels, and usually we refer loosely to the rows indices as **index** and the column indices as **column names**. Proper indexing is what provides us with efficient ways of finding data across our datasets.

**Indexing** is then the process of selecting particular rows and columns of data from a DataFrame, using this address system. 

In [ ]:
# Read the data in file netflix_titles.csv into a pandas DataFrame and use column show_id as the DataFrame index.

In [61]:
movies = pd.read_csv('Data/netflix_titles.csv', index_col = 'show_id')

In [62]:
movies.head(5)

type                            title           director  \
show_id                                                              
247747   Movie               Amar Akbar Anthony     Manmohan Desai   
269880   Movie                         Bad Boys        Michael Bay   
281550   Movie                         La Bamba        Luis Valdez   
284890   Movie                          Barsaat  Rajkumar Santoshi   
292118   Movie  Beavis and Butt-head Do America         Mike Judge   

                                                      cast        country  \
show_id                                                                     
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880   Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890   Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118   Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   

                date_added  release_year rating duration           listed_in  \
show_id                                                                        
247747   December 31, 2019          1977  TV-14  172 min  Action & Adventure   
269880     October 1, 2019          1995      R  119 min  Action & Adventure   
281550     January 1, 2020          1987  PG-13  109 min      Classic Movies   
284890       April 1, 2018          1995  TV-PG  166 min  Action & Adventure   
292118   November 20, 2019          1996  PG-13   81 min            Comedies   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
269880   In this fast-paced actioner, two Miami narcoti...  
281550   The plane crash that killed Buddy Holly also t...  
284890   A naïve young man and a rich city girl fall in...  
292118   After realizing that their boob tube is gone, ...

## Selecting columns

As mentioned before, **indexing** is what we call the process of selecting particular rows and columns of data from a DataFrame. We'll start by seeing how we can make use of the columns' indices - the __column names__ - to perform this task. 

There are two ways of doing this:

* using dot notation (`dataframe.column_name`)
* using braket notation (`dataframe[column_name]`)

In [63]:
movies.title

show_id
247747                          Amar Akbar Anthony
269880                                    Bad Boys
281550                                    La Bamba
284890                                     Barsaat
292118             Beavis and Butt-head Do America
                             ...                  
81224868                              Robot Trains
81227195    Kalushi: The Story of Solomon Mahlangu
81228864                           Blitz Patrollie
81235603                          Sym-Bionic Titan
81235729                                   Jezebel
Name: title, Length: 6234, dtype: object

In [64]:
movies["director"]

show_id
247747         Manmohan Desai
269880            Michael Bay
281550            Luis Valdez
284890      Rajkumar Santoshi
292118             Mike Judge
                  ...        
81224868                  NaN
81227195          Mandla Dube
81228864       Andrew Wessels
81235603                  NaN
81235729         Numa Perrier
Name: director, Length: 6234, dtype: object

Now try selecting multiple columns, such as __country__ and __release_year__. Notice that the output of the multiple selection is now a __Dataframe__ itself, containing the index and both columns selected

In [65]:
movies[["country", "release_year"]]

country  release_year
show_id                              
247747            India          1977
269880    United States          1995
281550    United States          1987
284890            India          1995
292118    United States          1996
...                 ...           ...
81224868    South Korea          2018
81227195   South Africa          2016
81228864   South Africa          2013
81235603  United States          2010
81235729  United States          2019

[6234 rows x 2 columns]

## Selecting rows

We'll now use the rows labels - the dataframe index - to select rows. We will show you two ways of doing this:

* Selecting rows by index position (`iloc`)
* Selecting rows by index labels (`loc`)

### Selecting rows by index position - iloc

With function `iloc` you can select specific rows from a DataFrame, by their position in the index. To do this, you specify one integer, a list of integers or a slice. All indices specified should be between 0 and Dataframe length minus 1 (remember that Python starts indexing with a 0)

See how you can select the first row with this method. Notice that the output produced is a __Series__.

In [66]:
movies.iloc[0]

type                                                        Movie
title                                          Amar Akbar Anthony
director                                           Manmohan Desai
cast            Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...
country                                                     India
date_added                                      December 31, 2019
release_year                                                 1977
rating                                                      TV-14
duration                                                  172 min
listed_in                                      Action & Adventure
description     Abandoned in a park by their father, Amar, Akb...
Name: 247747, dtype: object

Now use a list of indices to fetch multiple rows. Notice that the output produced is now a __Dataframe__.

In [67]:
movies.iloc[[0, 2, 4, 6]]

type                            title        director  \
show_id                                                           
247747   Movie               Amar Akbar Anthony  Manmohan Desai   
281550   Movie                         La Bamba     Luis Valdez   
292118   Movie  Beavis and Butt-head Do America      Mike Judge   
347365   Movie                         Candyman    Bernard Rose   

                                                      cast  \
show_id                                                      
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...   
292118   Mike Judge, Bruce Willis, Demi Moore, Cloris L...   
347365   Virginia Madsen, Tony Todd, Xander Berkeley, K...   

                               country         date_added  release_year  \
show_id                                                                   
247747                           India  December 31, 2019          1977   
281550                   United States    January 1, 2020          1987   
292118                   United States  November 20, 2019          1996   
347365   United States, United Kingdom    October 1, 2019          1992   

        rating duration           listed_in  \
show_id                                       
247747   TV-14  172 min  Action & Adventure   
281550   PG-13  109 min      Classic Movies   
292118   PG-13   81 min            Comedies   
347365       R   99 min         Cult Movies   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
281550   The plane crash that killed Buddy Holly also t...  
292118   After realizing that their boob tube is gone, ...  
347365   Grad student Helen Lyle unintentionally summon...

In [68]:
# Get first 4 rows
movies.iloc[:4]

type               title           director  \
show_id                                                 
247747   Movie  Amar Akbar Anthony     Manmohan Desai   
269880   Movie            Bad Boys        Michael Bay   
281550   Movie            La Bamba        Luis Valdez   
284890   Movie             Barsaat  Rajkumar Santoshi   

                                                      cast        country  \
show_id                                                                     
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880   Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890   Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   

                date_added  release_year rating duration           listed_in  \
show_id                                                                        
247747   December 31, 2019          1977  TV-14  172 min  Action & Adventure   
269880     October 1, 2019          1995      R  119 min  Action & Adventure   
281550     January 1, 2020          1987  PG-13  109 min      Classic Movies   
284890       April 1, 2018          1995  TV-PG  166 min  Action & Adventure   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
269880   In this fast-paced actioner, two Miami narcoti...  
281550   The plane crash that killed Buddy Holly also t...  
284890   A naïve young man and a rich city girl fall in...

In [69]:
# Get all rows from row 5432 to the last row
movies.iloc[5432:]

type                                   title        director  \
show_id                                                                     
81035877    Movie                       Bewildered Bolbol    Khaled Marei   
81035878    Movie                        The Consul's Son       Amr Arafa   
81035879    Movie                   Three-Quarters Decent   Mohamed Hamdy   
81035880    Movie                        Hamza's Suitcase    Akram Farouk   
81035881    Movie                                   Farce       Shadi Ali   
...           ...                                     ...             ...   
81224868  TV Show                            Robot Trains             NaN   
81227195    Movie  Kalushi: The Story of Solomon Mahlangu     Mandla Dube   
81228864    Movie                         Blitz Patrollie  Andrew Wessels   
81235603  TV Show                        Sym-Bionic Titan             NaN   
81235729    Movie                                 Jezebel    Numa Perrier   

                                                       cast        country  \
show_id                                                                      
81035877  Ahmed Helmy, Zeina, Shery Adel, Emy Samir Ghan...          Egypt   
81035878  Khaled Saleh, Ghada Adel, Ahmed el-Sakka, Khal...          Egypt   
81035879  Mohamed Ragab, Lamitta Frangieh, Mohsen Mansou...            NaN   
81035880  Hamada Helal, Yousra El Lozy, Ahmed Fathy, Moh...          Egypt   
81035881  Ahmed Fathy, Bayoumi Fouad, Sami Maghouri, Moh...          Egypt   
...                                                     ...            ...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...    South Korea   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   South Africa   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   South Africa   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...  United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                  date_added  release_year rating   duration  \
show_id                                                        
81035877       June 20, 2019          2010  TV-14    112 min   
81035878      April 25, 2019          2011  TV-14    114 min   
81035879       June 20, 2019          2010  TV-MA     96 min   
81035880         May 2, 2019          2017  TV-14     79 min   
81035881        June 6, 2019          2017  TV-MA     94 min   
...                      ...           ...    ...        ...   
81224868   December 31, 2019          2018  TV-Y7  2 Seasons   
81227195   November 29, 2019          2016  TV-MA    107 min   
81228864   December 27, 2019          2013  TV-MA    102 min   
81235603   December 15, 2019          2010  TV-PG   1 Season   
81235729    January 16, 2020          2019  TV-MA     86 min   

                   listed_in  \
show_id                        
81035877            Comedies   
81035878            Comedies   
81035879            Comedies   
81035880            Comedies   
81035881            Comedies   
...                      ...   
81224868            Kids' TV   
81227195              Dramas   
81228864  Action & Adventure   
81235603            Kids' TV   
81235729              Dramas   

                                                description  
show_id                                                      
81035877  A man suffering from amnesia can't seem to cho...  
81035878  A notorious forger known for his ability to cr...  
81035879  Determined to fight corruption in his country,...  
81035880  When a con man tries to retrieve a bag of mone...  
81035881  A beauty expert, a drug dealer and a bungling ...  
...                                                     ...  
81224868  Keeping peace and safety in Train World is no ...  
81227195  The life and times of iconic South African lib...  
81228864  Caught between family pressures and small-time...  
81235603  Aliens fleeing their planet land on Earth, pos...  
81

Another possibility when slicing is to pick only part of the elements in the provided range, by a given __step__. This will mean that we only select one row every `step` rows. This notation follows:

`start_row:end_row:step`

See how this works by selecting the first 10 columns with a step of 2.

In [70]:
movies.iloc[0:10:2,:]

type                            title        director  \
show_id                                                           
247747   Movie               Amar Akbar Anthony  Manmohan Desai   
281550   Movie                         La Bamba     Luis Valdez   
292118   Movie  Beavis and Butt-head Do America      Mike Judge   
347365   Movie                         Candyman    Bernard Rose   
372195   Movie                     Child's Play     Tom Holland   

                                                      cast  \
show_id                                                      
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...   
292118   Mike Judge, Bruce Willis, Demi Moore, Cloris L...   
347365   Virginia Madsen, Tony Todd, Xander Berkeley, K...   
372195   Catherine Hicks, Alex Vincent, Brad Dourif, Ch...   

                               country         date_added  release_year  \
show_id                                                                   
247747                           India  December 31, 2019          1977   
281550                   United States    January 1, 2020          1987   
292118                   United States  November 20, 2019          1996   
347365   United States, United Kingdom    October 1, 2019          1992   
372195                   United States  December 31, 2019          1988   

        rating duration           listed_in  \
show_id                                       
247747   TV-14  172 min  Action & Adventure   
281550   PG-13  109 min      Classic Movies   
292118   PG-13   81 min            Comedies   
347365       R   99 min         Cult Movies   
372195       R   87 min         Cult Movies   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
281550   The plane crash that killed Buddy Holly also t...  
292118   After realizing that their boob tube is gone, ...  
347365   Grad student Helen Lyle unintentionally summon...  
372195   When a rash of murders unfolds, 6-year-old And...

In [73]:
movies.iloc[0:10:2,[0,4]]

type                        country
show_id                                      
247747   Movie                          India
281550   Movie                  United States
292118   Movie                  United States
347365   Movie  United States, United Kingdom
372195   Movie                  United States

### Selecting rows by index name - loc

Selecting by position is useful but oftentimes we want to specify the label to use to find a given row. You can do this with function `loc`. It follows the same notation of `iloc` but the content you are providing is an actual label. 

Let's see how you can do this. Start by selecting the row with __room_id__ 29396. Notice that once again, when you select only one row, a __Series__ object is returned.

In [74]:
movies.loc[247747]

type                                                        Movie
title                                          Amar Akbar Anthony
director                                           Manmohan Desai
cast            Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...
country                                                     India
date_added                                      December 31, 2019
release_year                                                 1977
rating                                                      TV-14
duration                                                  172 min
listed_in                                      Action & Adventure
description     Abandoned in a park by their father, Amar, Akb...
Name: 247747, dtype: object

Similarly to the `iloc` function, you can also pass lists or slices of labels. You should get __Dataframe__ objects back.

In [75]:
movies.loc[[247747,372195]]

type               title        director  \
show_id                                              
247747   Movie  Amar Akbar Anthony  Manmohan Desai   
372195   Movie        Child's Play     Tom Holland   

                                                      cast        country  \
show_id                                                                     
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
372195   Catherine Hicks, Alex Vincent, Brad Dourif, Ch...  United States   

                date_added  release_year rating duration           listed_in  \
show_id                                                                        
247747   December 31, 2019          1977  TV-14  172 min  Action & Adventure   
372195   December 31, 2019          1988      R   87 min         Cult Movies   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
372195   When a rash of murders unfolds, 6-year-old And...

## Multi-axis indexing

Selecting by rows or by columns corresponds to indexing by only one axis (we normally depict rows as axis 0 and columns as axis 1). However, one nice thing about loc and iloc is that it allows for multi-axis indexing, this is, we can select columns and rows at the same time. 

Let's use the `iloc` to select based on the position of the rows and columns to pick the last five rows and the first 3 columns.

In [76]:
movies.iloc[-5:,:3]

type                                   title        director
show_id                                                                  
81224868  TV Show                            Robot Trains             NaN
81227195    Movie  Kalushi: The Story of Solomon Mahlangu     Mandla Dube
81228864    Movie                         Blitz Patrollie  Andrew Wessels
81235603  TV Show                        Sym-Bionic Titan             NaN
81235729    Movie                                 Jezebel    Numa Perrier

Let's now use the `loc` to select based on the names of the rows and columns to pick the _title_ and _country_ of the show_id 347365 and 81224868.

In [77]:
movies.loc[[347365, 81224868], ["title", "country"]]

title                        country
show_id                                              
347365        Candyman  United States, United Kingdom
81224868  Robot Trains                    South Korea



## Subsetting data using mask and where 

When we are doing analysis on data, we usually want to filter it or select it according to certain conditons. Pandas dataframes provide two inbuilt methods that are useful to filter data according to a condition or a set of conditions:

* `DataFrame.mask` - Replace value when condition is true
* `DataFrame.where` - Replace value when condition is false



### Mask

The `mask` function replaces values when the condition passed is `True`, so it can be used to "hide" rows given a condition. These rows will have all values replaced by NaN:

In [78]:
movies.mask(movies.release_year <= 1988)

type                                   title           director  \
show_id                                                                        
247747        NaN                                     NaN                NaN   
269880      Movie                                Bad Boys        Michael Bay   
281550        NaN                                     NaN                NaN   
284890      Movie                                 Barsaat  Rajkumar Santoshi   
292118      Movie         Beavis and Butt-head Do America         Mike Judge   
...           ...                                     ...                ...   
81224868  TV Show                            Robot Trains                NaN   
81227195    Movie  Kalushi: The Story of Solomon Mahlangu        Mandla Dube   
81228864    Movie                         Blitz Patrollie     Andrew Wessels   
81235603  TV Show                        Sym-Bionic Titan                NaN   
81235729    Movie                                 Jezebel       Numa Perrier   

                                                       cast        country  \
show_id                                                                      
247747                                                  NaN            NaN   
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550                                                  NaN            NaN   
284890    Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   
...                                                     ...            ...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...    South Korea   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   South Africa   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   South Africa   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...  United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                  date_added  release_year rating   duration  \
show_id                                                        
247747                   NaN           NaN    NaN        NaN   
269880       October 1, 2019        1995.0      R    119 min   
281550                   NaN           NaN    NaN        NaN   
284890         April 1, 2018        1995.0  TV-PG    166 min   
292118     November 20, 2019        1996.0  PG-13     81 min   
...                      ...           ...    ...        ...   
81224868   December 31, 2019        2018.0  TV-Y7  2 Seasons   
81227195   November 29, 2019        2016.0  TV-MA    107 min   
81228864   December 27, 2019        2013.0  TV-MA    102 min   
81235603   December 15, 2019        2010.0  TV-PG   1 Season   
81235729    January 16, 2020        2019.0  TV-MA     86 min   

                   listed_in  \
show_id                        
247747                   NaN   
269880    Action & Adventure   
281550                   NaN   
284890    Action & Adventure   
292118              Comedies   
...                      ...   
81224868            Kids' TV   
81227195              Dramas   
81228864  Action & Adventure   
81235603            Kids' TV   
81235729              Dramas   

                                                description  
show_id                                                      
247747                                                  NaN  
269880    In this fast-paced actioner, two Miami narcoti...  
281550                                                  NaN  
284890    A naïve young man and a rich city girl fall in...  
292118    After realizing that their boob tube is gone, ...  
...                                                     ...  
81224868  Keeping peace and safety in Train World is no ...  
81227195  The life and times of iconic South African lib...  
81228864  Caught between family pressures and small-time...  
81235603  Aliens fleeing 

You can leave only the non-hidden values by dropping the NaN rows. Pandas already provides a function for that, `dropna`. 

__Hint__: notice the argument `how=all` in the function. This means that only masked rows - rows where __all__ elements are set to `NaN` - are dropped. 

In [79]:
movies.mask(movies.release_year <= 1988).dropna(how='all')

type                                   title           director  \
show_id                                                                        
269880      Movie                                Bad Boys        Michael Bay   
284890      Movie                                 Barsaat  Rajkumar Santoshi   
292118      Movie         Beavis and Butt-head Do America         Mike Judge   
347365      Movie                                Candyman       Bernard Rose   
404067      Movie                               The Craft     Andrew Fleming   
...           ...                                     ...                ...   
81224868  TV Show                            Robot Trains                NaN   
81227195    Movie  Kalushi: The Story of Solomon Mahlangu        Mandla Dube   
81228864    Movie                         Blitz Patrollie     Andrew Wessels   
81235603  TV Show                        Sym-Bionic Titan                NaN   
81235729    Movie                                 Jezebel       Numa Perrier   

                                                       cast  \
show_id                                                       
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...   
284890    Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...   
347365    Virginia Madsen, Tony Todd, Xander Berkeley, K...   
404067    Robin Tunney, Fairuza Balk, Neve Campbell, Rac...   
...                                                     ...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...   

                                country          date_added  release_year  \
show_id                                                                     
269880                    United States     October 1, 2019        1995.0   
284890                            India       April 1, 2018        1995.0   
292118                    United States   November 20, 2019        1996.0   
347365    United States, United Kingdom     October 1, 2019        1992.0   
404067                    United States     January 1, 2020        1996.0   
...                                 ...                 ...           ...   
81224868                    South Korea   December 31, 2019        2018.0   
81227195                   South Africa   November 29, 2019        2016.0   
81228864                   South Africa   December 27, 2019        2013.0   
81235603                  United States   December 15, 2019        2010.0   
81235729                  United States    January 16, 2020        2019.0   

         rating   duration           listed_in  \
show_id                                          
269880        R    119 min  Action & Adventure   
284890    TV-PG    166 min  Action & Adventure   
292118    PG-13     81 min            Comedies   
347365        R     99 min         Cult Movies   
404067        R    101 min       Horror Movies   
...         ...        ...                 ...   
81224868  TV-Y7  2 Seasons            Kids' TV   
81227195  TV-MA    107 min              Dramas   
81228864  TV-MA    102 min  Action & Adventure   
81235603  TV-PG   1 Season            Kids' TV   
81235729  TV-MA     86 min              Dramas   

                                                description  
show_id                                                      
269880    In this fast-paced actioner, two Miami narcoti...  
284890    A naïve young man and a rich city girl fall in...  
292118    After realizing that their boob tube is gone, ...  
347365    Grad student Helen Lyle unintentionally summon...  
404067    At a Catholic school, a new girl falls in with...  
...                                                     ...  
812

## Where

The `where` function, on the other hand, can be used to hide the rows that __do not__ verify a certain condition, leaving only the rows that do verify it. The "hidden" rows will have all values replaced by NaN.

In [80]:
movies.where(movies.release_year <= 1988)

type               title        director  \
show_id                                               
247747    Movie  Amar Akbar Anthony  Manmohan Desai   
269880      NaN                 NaN             NaN   
281550    Movie            La Bamba     Luis Valdez   
284890      NaN                 NaN             NaN   
292118      NaN                 NaN             NaN   
...         ...                 ...             ...   
81224868    NaN                 NaN             NaN   
81227195    NaN                 NaN             NaN   
81228864    NaN                 NaN             NaN   
81235603    NaN                 NaN             NaN   
81235729    NaN                 NaN             NaN   

                                                       cast        country  \
show_id                                                                      
247747    Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880                                                  NaN            NaN   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890                                                  NaN            NaN   
292118                                                  NaN            NaN   
...                                                     ...            ...   
81224868                                                NaN            NaN   
81227195                                                NaN            NaN   
81228864                                                NaN            NaN   
81235603                                                NaN            NaN   
81235729                                                NaN            NaN   

                 date_added  release_year rating duration           listed_in  \
show_id                                                                         
247747    December 31, 2019        1977.0  TV-14  172 min  Action & Adventure   
269880                  NaN           NaN    NaN      NaN                 NaN   
281550      January 1, 2020        1987.0  PG-13  109 min      Classic Movies   
284890                  NaN           NaN    NaN      NaN                 NaN   
292118                  NaN           NaN    NaN      NaN                 NaN   
...                     ...           ...    ...      ...                 ...   
81224868                NaN           NaN    NaN      NaN                 NaN   
81227195                NaN           NaN    NaN      NaN                 NaN   
81228864                NaN           NaN    NaN      NaN                 NaN   
81235603                NaN           NaN    NaN      NaN                 NaN   
81235729                NaN           NaN    NaN      NaN                 NaN   

                                                description  
show_id                                                      
247747    Abandoned in a park by their father, Amar, Akb...  
269880                                                  NaN  
281550    The plane crash that killed Buddy Holly also t...  
284890                                                  NaN  
292118                                                  NaN  
...                                                     ...  
81224868                                                NaN  
81227195                                                NaN  
81228864                                                NaN  
81235603                                                NaN  
81235729                                                NaN  

[6234 rows x 11 columns]

Once again, we can leave only non-hidden values by using `dropna`

In [81]:
movies.where(movies.release_year <= 1988).dropna(how='all')

type               title        director  \
show_id                                               
247747    Movie  Amar Akbar Anthony  Manmohan Desai   
281550    Movie            La Bamba     Luis Valdez   
296682    Movie               Benji        Joe Camp   
352989    Movie              Carrie  Brian De Palma   
372195    Movie        Child's Play     Tom Holland   
...         ...                 ...             ...   
81213897  Movie        Namak Halaal   Prakash Mehra   
81213898  Movie   The Great Gambler  Shakti Samanta   
81213979  Movie              Masoom   Shekhar Kapur   
81217437  Movie               Mandi   Shyam Benegal   
81221914  Movie         Saath Saath     Raman Kumar   

                                                       cast        country  \
show_id                                                                      
247747    Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
296682    Benji, Deborah Walley, Peter Breck, Edgar Buch...  United States   
352989    Sissy Spacek, Piper Laurie, Amy Irving, Willia...  United States   
372195    Catherine Hicks, Alex Vincent, Brad Dourif, Ch...  United States   
...                                                     ...            ...   
81213897  Amitabh Bachchan, Shashi Kapoor, Parveen Babi,...          India   
81213898  Amitabh Bachchan, Zeenat Aman, Neetu Singh, Pr...          India   
81213979  Shabana Azmi, Naseeruddin Shah, Saeed Jaffrey,...          India   
81217437  Shabana Azmi, Smita Patil, Naseeruddin Shah, A...          India   
81221914  Deepti Naval, Farooq Shaikh, Satish Shah, Ifte...          India   

                 date_added  release_year rating duration  \
show_id                                                     
247747    December 31, 2019        1977.0  TV-14  172 min   
281550      January 1, 2020        1987.0  PG-13  109 min   
296682        March 6, 2018        1974.0      G   86 min   
352989         June 1, 2019        1976.0      R   98 min   
372195    December 31, 2019        1988.0      R   87 min   
...                     ...           ...    ...      ...   
81213897  December 31, 2019        1982.0  TV-14  171 min   
81213898  December 31, 2019        1979.0  TV-14  161 min   
81213979  December 31, 2019        1983.0  TV-14  138 min   
81217437    January 1, 2020        1983.0  TV-MA  155 min   
81221914  December 31, 2019        1982.0  TV-14  118 min   

                         listed_in  \
show_id                              
247747          Action & Adventure   
281550              Classic Movies   
296682    Children & Family Movies   
352989              Classic Movies   
372195                 Cult Movies   
...                            ...   
81213897        Action & Adventure   
81213898        Action & Adventure   
81213979                    Dramas   
81217437                    Dramas   
81221914                    Dramas   

                                                description  
show_id                                                      
247747    Abandoned in a park by their father, Amar, Akb...  
281550    The plane crash that killed Buddy Holly also t...  
296682    After lovable abandoned mutt Benji is adopted ...  
352989    An outcast teen with telekinetic ability lashe...  
372195    When a rash of murders unfolds, 6-year-old And...  
...                                                     ...  
81213897  While loyally defending his boss from mobsters...  
81213898  After unwittingly using his skills to obtain m...  
81213979  A loving husband and father's joyful family li...  
81217437  Forbidden love, fraying loyalties and flagrant...  
81221914  A young woman falls for her classmate’s ideali...  

[177 rows x 11 columns]

Basically __mask__ and __where__ do the opposite of each other! One is used to choose data given a condition and the other one is used to hide data given a condition. Applying the same condition to both and dropping "hidden" rows, you'll get complementary sets of your data.

## Subsetting data on conditions

Besides relying on `mask` and `where`, we can also use the __bracket notation__ with conditions to subset data from the DataFrame. By doing this, we get a DataFrame that most likely has a different shape from the initial one, since it only returns the subset of its rows that satisfy the condition.

Let's subset the DataFrame to get all the movies released in 1988. Note the DataFrame shape!

__Note__:  this is different from what we saw in the mask/filter functions: those functions don't change the DataFame shape, instead, they just replace the values that we don't want with NaNs. 

In [82]:
movies[movies.release_year == 1988]

type                                           title  \
show_id                                                             
372195      Movie                                    Child's Play   
20254278    Movie                                  Aakhri Adaalat   
60001807    Movie  The Naked Gun: From the Files of Police Squad!   
60003961    Movie            Thelonious Monk: Straight, No Chaser   
60029369    Movie                                        Rain Man   
70157402  TV Show                               Highway to Heaven   
70206819    Movie      Quiet Victory: The Charlie Wedemeyer Story   
70206821    Movie                      A Stoning in Fulham County   
70206823    Movie                              Too Young the Hero   
70208520  TV Show                                       High Risk   
80023921    Movie          Pee-wee's Playhouse: Christmas Special   
80201618    Movie                             Maza Pati Karodpati   
80997859    Movie                                   Painted Faces   

                         director  \
show_id                             
372195                Tom Holland   
20254278              Rajiv Mehra   
60001807             David Zucker   
60003961         Charlotte Zwerin   
60029369           Barry Levinson   
70157402                      NaN   
70206819        Roy Campanella II   
70206821            Larry Elikann   
70206823               Buzz Kulik   
70208520                      NaN   
80023921  Paul Reubens, Wayne Orr   
80201618                   Sachin   
80997859                 Alex Law   

                                                       cast        country  \
show_id                                                                      
372195    Catherine Hicks, Alex Vincent, Brad Dourif, Ch...  United States   
20254278  Vinod Khanna, Dimple Kapadia, Jackie Shroff, S...          India   
60001807  Leslie Nielsen, Priscilla Presley, Ricardo Mon...  United States   
60003961                  Thelonious Monk, Samuel E. Wright  United States   
60029369  Dustin Hoffman, Tom Cruise, Valeria Golino, Ge...  United States   
70157402                      Michael Landon, Victor French  United States   
70206819  Pam Dawber, Michael Nouri, Bess Meyer, Peter B...  United States   
70206821  Ken Olin, Jill Eikenberry, Maureen Mueller, Gr...  United States   
70206823  Ricky Schroder, Jon DeVries, Debra Mooney, Mar...  United States   
70208520                                                NaN  United States   
80023921  Paul Reubens, Annette Funicello, Frankie Avalo...  United States   
80201618  Sachin, Supriya Pilgaonkar, Ashok Saraf, Kisho...          India   
80997859   Sammo Kam-Bo Hung, Ching-Ying Lam, Cheng Pei-pei      Hong Kong   

                 date_added  release_year rating   duration  \
show_id                                                       
372195    December 31, 2019          1988      R     87 min   
20254278  September 1, 2017          1988  TV-14    148 min   
60001807    January 1, 2020          1988  PG-13     85 min   
60003961   November 1, 2019          1988  PG-13     89 min   
60029369       July 1, 2019          1988      R    134 min   
70157402   November 1, 2016          1988  TV-PG  5 Seasons   
70206819    October 1, 2011          1988  TV-PG     93 min   
70206821    October 1, 2011          1988     NR     95 min   
70206823    October 1, 2011          1988     NR     94 min   
70208520  September 1, 2017          1988   TV-G   1 Season   
80023921  December 18, 2014          1988  TV-PG     48 min   
80201618    January 1, 2018          1988  TV-PG    132 min   
80997859    August 16, 2018          1988  TV-PG    108 min   

                   listed_in  \
show_id                        
372195           Cult Movies   
20254278  Action & Adventure   
60001807            Comedies   
60003961       Documentaries   
60029369      Classic Movies   
70157402           TV Dramas   
70206819              Dramas   
70206821        

We can combine conditions, for example subsetting Tv Shows from 1988:

In [83]:
movies[(movies.release_year == 1988) & (movies.type == 'TV Show')]

type              title director                           cast  \
show_id                                                                        
70157402  TV Show  Highway to Heaven      NaN  Michael Landon, Victor French   
70208520  TV Show          High Risk      NaN                            NaN   

                country         date_added  release_year rating   duration  \
show_id                                                                      
70157402  United States   November 1, 2016          1988  TV-PG  5 Seasons   
70208520  United States  September 1, 2017          1988   TV-G   1 Season   

           listed_in                                        description  
show_id                                                                  
70157402   TV Dramas  Under God's direction, angel Jonathan and ex-c...  
70208520  Docuseries  From scientists to snake handlers, this series...

__Note the parenthesis around each condition, they're required!__

### Special conditions

There are different types of conditions you may want to provide, and it is useful to know some of the basics operators you can use to subset:

- values of a column are equal to a specific value: `==` works for any type
- values of a column are __not__ equal to a specific value: `!=` works for any type
- other basic operator on numeric values:
   - Greater than, less than: `>` or `<`
   - Greater than or equal to `>=`
   - Less than or equal to `<=`
- values of a column are in a list of values: `isin` method 
- negate conditions with `~`  

The first three are either represented above, or are small variations of it. Play around with those to see different outcomes. The last two, however, might seem new to you. Let's look a bit more into those.


#### Matching values in a list

Sometimes you don't want to test equality with one value, but instead you want to check for several possible values. Even though you could match with each of the values in your list, as shown below:

In [84]:
# e.g. matching content in english
movies[movies.country.isin(["United States", "United Kingdom", "Australia", "New Zealand"])]

type                            title  \
show_id                                              
269880      Movie                         Bad Boys   
281550      Movie                         La Bamba   
292118      Movie  Beavis and Butt-head Do America   
296682      Movie                            Benji   
352989      Movie                           Carrie   
...           ...                              ...   
81218079    Movie                            Awake   
81221873    Movie                             Zoom   
81224128  TV Show                  The Repair Shop   
81235603  TV Show                 Sym-Bionic Titan   
81235729    Movie                          Jezebel   

                                  director  \
show_id                                      
269880                         Michael Bay   
281550                         Luis Valdez   
292118                          Mike Judge   
296682                            Joe Camp   
352989                      Brian De Palma   
...                                    ...   
81218079  Aleksandr Chernyaev, Fedor Lyass   
81221873                      Peter Hewitt   
81224128                               NaN   
81235603                               NaN   
81235729                      Numa Perrier   

                                                       cast         country  \
show_id                                                                       
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...   United States   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...   United States   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...   United States   
296682    Benji, Deborah Walley, Peter Breck, Edgar Buch...   United States   
352989    Sissy Spacek, Piper Laurie, Amy Irving, Willia...   United States   
...                                                     ...             ...   
81218079  Jonathan Rhys Meyers, Francesca Eastwood, Mali...   United States   
81221873  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...   United States   
81224128                                                NaN  United Kingdom   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...   United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...   United States   

                 date_added  release_year rating   duration  \
show_id                                                       
269880      October 1, 2019          1995      R    119 min   
281550      January 1, 2020          1987  PG-13    109 min   
292118    November 20, 2019          1996  PG-13     81 min   
296682        March 6, 2018          1974      G     86 min   
352989         June 1, 2019          1976      R     98 min   
...                     ...           ...    ...        ...   
81218079  November 24, 2019          2019  TV-MA     92 min   
81221873   January 11, 2020          2006     PG     88 min   
81224128   December 1, 2019          2018     PG  2 Seasons   
81235603  December 15, 2019          2010  TV-PG   1 Season   
81235729   January 16, 2020          2019  TV-MA     86 min   

                         listed_in  \
show_id                              
269880          Action & Adventure   
281550              Classic Movies   
292118                    Comedies   
296682    Children & Family Movies   
352989              Classic Movies   
...                            ...   
81218079                 Thrillers   
81221873  Children & Family Movies   
81224128          British TV Shows   
81235603                  Kids' TV   
81235729                    Dramas   

                                                description  
show_id                                                      
269880    In this fast-paced actioner, two Miami narcoti...  
281550    The plane crash that killed Buddy Holly also t...  
292118    After realizing that their boob tube is gone, ...  
296682    After lovable abandoned mutt Benji is adopted ..

#### Negating a condition

What if we wanted to say that a given value is not in the desired list? Or if we just wanted to negate the conditions that were given to sample the "excluded" data. There are many ways to do this, but a very easy one is to use the `~` operator behind your conditions.

See the following examples to understand how this works. Let's start with a simple one using only one condition:

In [85]:
movies[movies.type == 'Movie']

type                                   title           director  \
show_id                                                                      
247747    Movie                      Amar Akbar Anthony     Manmohan Desai   
269880    Movie                                Bad Boys        Michael Bay   
281550    Movie                                La Bamba        Luis Valdez   
284890    Movie                                 Barsaat  Rajkumar Santoshi   
292118    Movie         Beavis and Butt-head Do America         Mike Judge   
...         ...                                     ...                ...   
81221913  Movie          Kuldip Patwal: I Didn't Do It!         Remy Kohli   
81221914  Movie                             Saath Saath        Raman Kumar   
81227195  Movie  Kalushi: The Story of Solomon Mahlangu        Mandla Dube   
81228864  Movie                         Blitz Patrollie     Andrew Wessels   
81235729  Movie                                 Jezebel       Numa Perrier   

                                                       cast        country  \
show_id                                                                      
247747    Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890    Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   
...                                                     ...            ...   
81221913  Deepak Dobriyal, Gulshan Devaiah, Raima Sen, P...          India   
81221914  Deepti Naval, Farooq Shaikh, Satish Shah, Ifte...          India   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   South Africa   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   South Africa   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                 date_added  release_year rating duration           listed_in  \
show_id                                                                         
247747    December 31, 2019          1977  TV-14  172 min  Action & Adventure   
269880      October 1, 2019          1995      R  119 min  Action & Adventure   
281550      January 1, 2020          1987  PG-13  109 min      Classic Movies   
284890        April 1, 2018          1995  TV-PG  166 min  Action & Adventure   
292118    November 20, 2019          1996  PG-13   81 min            Comedies   
...                     ...           ...    ...      ...                 ...   
81221913  December 31, 2019          2017  TV-MA  126 min              Dramas   
81221914  December 31, 2019          1982  TV-14  118 min              Dramas   
81227195  November 29, 2019          2016  TV-MA  107 min              Dramas   
81228864  December 27, 2019          2013  TV-MA  102 min  Action & Adventure   
81235729   January 16, 2020          2019  TV-MA   86 min              Dramas   

                                                description  
show_id                                                      
247747    Abandoned in a park by their father, Amar, Akb...  
269880    In this fast-paced actioner, two Miami narcoti...  
281550    The plane crash that killed Buddy Holly also t...  
284890    A naïve young man and a rich city girl fall in...  
292118    After realizing that their boob tube is gone, ...  
...                                                     ...  
81221913  Accused of killing a politician, a local groce...  
81221914  A young woman falls for her classmate’s ideali...  
81227195  The life and times of iconic South African lib...  
81228864  Caught between family pressures and small-time...  
81235729  During the internet's infancy, a vulnerable wo...  

[4265 rows x 11 columns]

Negate the previous condition

In [86]:
movies[~(movies.type == 'Movie')]

type               title director  \
show_id                                          
60036794  TV Show             Sonic X      NaN   
70136114  TV Show          The L Word      NaN   
70136120  TV Show   The Office (U.S.)      NaN   
70136122  TV Show               Weeds      NaN   
70136126  TV Show              Dexter      NaN   
...           ...                 ...      ...   
81224128  TV Show     The Repair Shop      NaN   
81224811  TV Show  Pucca: Love Recipe      NaN   
81224839  TV Show        Rainbow Ruby      NaN   
81224868  TV Show        Robot Trains      NaN   
81235603  TV Show    Sym-Bionic Titan      NaN   

                                                       cast  \
show_id                                                       
60036794  Suzanne Goldish, Dan Green, Jason Anthony Grif...   
70136114  Jennifer Beals, Leisha Hailey, Laurel Holloman...   
70136120  Steve Carell, John Krasinski, Jenna Fischer, R...   
70136122  Mary-Louise Parker, Hunter Parrish, Alexander ...   
70136126  Michael C. Hall, Jennifer Carpenter, David Zay...   
...                                                     ...   
81224128                                                NaN   
81224811  Jeonghwa Yang, Yongwoo Shin, Doug Erholtz, Mel...   
81224839  Alyssya Swales, Shannon Chan-Kent, Brian Drumm...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...   

                                            country          date_added  \
show_id                                                                   
60036794                                      Japan    December 1, 2019   
70136114                      Canada, United States      March 20, 2018   
70136120                              United States     January 1, 2016   
70136122                              United States       April 1, 2014   
70136126                              United States     January 1, 2018   
...                                             ...                 ...   
81224128                             United Kingdom    December 1, 2019   
81224811                                        NaN   December 31, 2019   
81224839  South Korea, Canada, United States, China   December 31, 2019   
81224868                                South Korea   December 31, 2019   
81235603                              United States   December 15, 2019   

          release_year rating   duration          listed_in  \
show_id                                                       
60036794          2004  TV-Y7  4 Seasons       Anime Series   
70136114          2009  TV-MA  6 Seasons  Romantic TV Shows   
70136120          2012  TV-14  9 Seasons        TV Comedies   
70136122          2012  TV-MA  8 Seasons        TV Comedies   
70136126          2013  TV-MA  8 Seasons     Crime TV Shows   
...                ...    ...        ...                ...   
81224128          2018     PG  2 Seasons   British TV Shows   
81224811          2018  TV-Y7   1 Season           Kids' TV   
81224839          2016   TV-Y   1 Season           Kids' TV   
81224868          2018  TV-Y7  2 Seasons           Kids' TV   
81235603          2010  TV-PG   1 Season           Kids' TV   

                                                description  
show_id                                                      
60036794  While battling the evil Dr. Eggman, Sonic gets...  
70136114  This trailblazing series follows the tangled l...  
70136120  This hit comedy chronicles the foibles of disg...  
70136122  A suburban mother starts selling marijuana to ...  
70136126  By day, mild-mannered Dexter is a blood-spatte...  
...                                                     ...  
81224128  Expert artisans restore timeworn family heirlo...  
81224811  Faced with a threat to the survival of her fam...  
81224839  Ruby makes magical journeys with her teddy bea...  
81224868  Keeping peace and safety in Train World is no ...  
81

### Combining conditions

In many cases you will want to sample according to several conditions. As you see above, you should wrap your conditions in between parentheses. There are two main ways of combining conditions:

* AND: if you want to make sure your data satisfies all conditions
* OR: if you want to make sure your data satisfies one of the conditions

Even though python has `and` and `or` as regular keywords for this, for pandas subsetting you should use `&` and `|`. When using the logical operators  `and` and `or` you are implicitly asking Python to convert the conditions to boolean values. Numpy arrays and thus pandas columns have no truth value. So we need to use the bitwise operators, which numpy makes use of to do element-wise operations, since unlike their logical counterparts, they can be overriden to return specific output values.



In [87]:
# Proper usage of & for element wise and
movies[(movies.type == 'Movie') & (movies.release_year >= 2019) & ~(movies.listed_in.isin(['Documentaries', 'Kids\' TV'])) & (movies.country == "United States")]

type                        title  \
show_id                                        
80134721  Movie                           IO   
80169469  Movie                     The Dirt   
80174687  Movie    Kevin Hart: Irresponsible   
80175798  Movie                 The Irishman   
80182014  Movie          Dolemite Is My Name   
...         ...                          ...   
81183570  Movie  Home Is Where the Killer Is   
81183572  Movie                 Deviant Love   
81214114  Movie                Bulletproof 2   
81218079  Movie                        Awake   
81235729  Movie                      Jezebel   

                                  director  \
show_id                                      
80134721                  Jonathan Helpert   
80169469                     Jeff Tremaine   
80174687                      Leslie Small   
80175798                   Martin Scorsese   
80182014                      Craig Brewer   
...                                    ...   
81183570                        Kaila York   
81183572                    Michael Feifer   
81214114                  Don Michael Paul   
81218079  Aleksandr Chernyaev, Fedor Lyass   
81235729                      Numa Perrier   

                                                       cast        country  \
show_id                                                                      
80134721     Margaret Qualley, Anthony Mackie, Danny Huston  United States   
80169469  Douglas Booth, Iwan Rheon, Colson Baker, Danie...  United States   
80174687                                         Kevin Hart  United States   
80175798  Robert De Niro, Al Pacino, Joe Pesci, Harvey K...  United States   
80182014  Eddie Murphy, Wesley Snipes, Keegan-Michael Ke...  United States   
...                                                     ...            ...   
81183570  Stacy Haiduk, Kelly Kruger, Christopher Sean, ...  United States   
81183572  Emma Bell, Nick Ballard, Bradley Bundlie, Gail...  United States   
81214114  Faizon Love, Kirk Fox, Tony Todd, Pearl Thusi,...  United States   
81218079  Jonathan Rhys Meyers, Francesca Eastwood, Mali...  United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                  date_added  release_year rating duration  \
show_id                                                      
80134721    January 18, 2019          2019  TV-14   96 min   
80169469      March 22, 2019          2019  TV-MA  108 min   
80174687       April 2, 2019          2019  TV-MA   60 min   
80175798   November 27, 2019          2019      R  209 min   
80182014    October 25, 2019          2019      R  118 min   
...                      ...           ...    ...      ...   
81183570     October 9, 2019          2019  TV-14   87 min   
81183572  September 13, 2019          2019  TV-14   87 min   
81214114     January 9, 2020          2020  TV-MA   97 min   
81218079   November 24, 2019          2019  TV-MA   92 min   
81235729    January 16, 2020          2019  TV-MA   86 min   

                   listed_in  \
show_id                        
80134721              Dramas   
80169469            Comedies   
80174687     Stand-Up Comedy   
80175798              Dramas   
80182014            Comedies   
...                      ...   
81183570              Dramas   
81183572           Thrillers   
81214114  Action & Adventure   
81218079           Thrillers   
81235729              Dramas   

                                                description  
show_id                                                      
80134721  As a young scientist searches for a way to sav...  
80169469  In this unflinching biopic based on Mötley Crü...  
80174687  As a father of three on his second marriage, K...  
80175798  Hit man Frank Sheeran looks back at the secret...  
80182014  In 1970s LA, struggling comedian Rudy Ray Moor...  
...                                                     ...  
81183570  Recovering from cancer, a young woman thin

In [88]:
# Proper usage of | for element wise and
movies[((movies.type == 'TV Show') | (movies.release_year >= 2019)) & (movies.listed_in.isin(['Dramas', 'Thrillers']))]

type                  title                          director  \
show_id                                                                    
80121387  Movie        Elisa & Marcela                     Isabel Coixet   
80134721  Movie                     IO                  Jonathan Helpert   
80174451  Movie          The Two Popes                Fernando Meirelles   
80175798  Movie           The Irishman                   Martin Scorsese   
80182016  Movie               The King                      David Michôd   
...         ...                    ...                               ...   
81206389  Movie  Oththa Seruppu Size 7                         Parthiban   
81217738  Movie              Dorasaani                      KVR Mahendra   
81217739  Movie              Mallesham                             Raj R   
81218079  Movie                  Awake  Aleksandr Chernyaev, Fedor Lyass   
81235729  Movie                Jezebel                      Numa Perrier   

                                                       cast  \
show_id                                                       
80121387  Natalia de Molina, Greta Fernández, Sara Casas...   
80134721     Margaret Qualley, Anthony Mackie, Danny Huston   
80174451      Anthony Hopkins, Jonathan Pryce, Juan Minujín   
80175798  Robert De Niro, Al Pacino, Joe Pesci, Harvey K...   
80182016  Timothée Chalamet, Joel Edgerton, Robert Patti...   
...                                                     ...   
81206389                                          Parthiban   
81217738  Anand Deverakonda, Shivatmika Rajasekhar, Kann...   
81217739     Jhansi, Priyadarshi Pullikonda, Ananya Nagalla   
81218079  Jonathan Rhys Meyers, Francesca Eastwood, Mali...   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...   

                                                  country         date_added  \
show_id                                                                        
80121387                                            Spain       June 7, 2019   
80134721                                    United States   January 18, 2019   
80174451  United Kingdom, Italy, Argentina, United States  December 20, 2019   
80175798                                    United States  November 27, 2019   
80182016                                              NaN   November 1, 2019   
...                                                   ...                ...   
81206389                                            India   November 4, 2019   
81217738                                            India  November 20, 2019   
81217739                                            India  November 20, 2019   
81218079                                    United States  November 24, 2019   
81235729                                    United States   January 16, 2020   

          release_year rating duration  listed_in  \
show_id                                             
80121387          2019  TV-MA  119 min     Dramas   
80134721          2019  TV-14   96 min     Dramas   
80174451          2019  PG-13  126 min     Dramas   
80175798          2019      R  209 min     Dramas   
80182016          2019      R  141 min     Dramas   
...                ...    ...      ...        ...   
81206389          2019  TV-MA  103 min     Dramas   
81217738          2019  TV-14  134 min     Dramas   
81217739          2019  TV-PG  131 min     Dramas   
81218079          2019  TV-MA   92 min  Thrillers   
81235729          2019  TV-MA   86 min     Dramas   

                                                description  
show_id                                                      
80121387  In 1901 Spain, Elisa Sánchez Loriga adopts a m...  
80134721  As a young scientist searches for a way to sav...  
80174451  At a key turning point for the Catholic Church...  
80175798  Hit man Frank Sheeran looks back at the secret...  
80182016  Wayward Prince Hal must turn from carouser to ...  
...                                  

## Adding Rows & Columns

### Adding or replacing a row

We can use the `loc` indexing operation to add a new row in a dataframe with a specific index. If dataframe already has any row with that index name then this will replace the contents of that row. See below an example of adding a non existing label:

In [89]:
new_movies_df = movies.copy()
original_size = len(new_movies_df.index)

# Add new movie to our dataframe with show_id=100
new_movies_df.loc[100] = ['TV Show','Gipfelstuermer','Jens Schnettler','Woodmark', 'Germany', 'June 25, 2020', 2016, '', '8 seasons', 'Documentaries', 'Roundhouse kick in the data world']
final_size = len(new_movies_df.index)

# Show our new movie
new_movies_df.loc[100]

type                                      TV Show
title                              Gipfelstuermer
director                          Jens Schnettler
cast                                     Woodmark
country                                   Germany
date_added                          June 25, 2020
release_year                                 2016
rating                                           
duration                                8 seasons
listed_in                           Documentaries
description     Roundhouse kick in the data world
Name: 100, dtype: object

In [91]:
print('Size of dataframe before: {} \nSize of dataframe after: {}'.format(original_size, final_size))

Size of dataframe before: 6234 
Size of dataframe after: 6235


### Adding or replacing a column

In the same way we did for rows, we can add a column to a daframe using the same notations that we used to select them, i.e., dot notation, brackets notation, or loc operator. 

In [92]:
# calculate the age of the movie instead of the release_year and replace it
new_movies_df['release_year'] = 2020 - new_movies_df.release_year

In [93]:
new_movies_df.head()

type                            title           director  \
show_id                                                              
247747   Movie               Amar Akbar Anthony     Manmohan Desai   
269880   Movie                         Bad Boys        Michael Bay   
281550   Movie                         La Bamba        Luis Valdez   
284890   Movie                          Barsaat  Rajkumar Santoshi   
292118   Movie  Beavis and Butt-head Do America         Mike Judge   

                                                      cast        country  \
show_id                                                                     
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880   Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890   Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118   Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   

                date_added  release_year rating duration           listed_in  \
show_id                                                                        
247747   December 31, 2019            43  TV-14  172 min  Action & Adventure   
269880     October 1, 2019            25      R  119 min  Action & Adventure   
281550     January 1, 2020            33  PG-13  109 min      Classic Movies   
284890       April 1, 2018            25  TV-PG  166 min  Action & Adventure   
292118   November 20, 2019            24  PG-13   81 min            Comedies   

                                               description  
show_id                                                     
247747   Abandoned in a park by their father, Amar, Akb...  
269880   In this fast-paced actioner, two Miami narcoti...  
281550   The plane crash that killed Buddy Holly also t...  
284890   A naïve young man and a rich city girl fall in...  
292118   After realizing that their boob tube is gone, ...

In [94]:
# you can create a new column instead
new_movies_df = movies.copy()
new_movies_df['age'] = 2020 - new_movies_df.release_year
new_movies_df.head()

type                            title           director  \
show_id                                                              
247747   Movie               Amar Akbar Anthony     Manmohan Desai   
269880   Movie                         Bad Boys        Michael Bay   
281550   Movie                         La Bamba        Luis Valdez   
284890   Movie                          Barsaat  Rajkumar Santoshi   
292118   Movie  Beavis and Butt-head Do America         Mike Judge   

                                                      cast        country  \
show_id                                                                     
247747   Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880   Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550   Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890   Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118   Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   

                date_added  release_year rating duration           listed_in  \
show_id                                                                        
247747   December 31, 2019          1977  TV-14  172 min  Action & Adventure   
269880     October 1, 2019          1995      R  119 min  Action & Adventure   
281550     January 1, 2020          1987  PG-13  109 min      Classic Movies   
284890       April 1, 2018          1995  TV-PG  166 min  Action & Adventure   
292118   November 20, 2019          1996  PG-13   81 min            Comedies   

                                               description  age  
show_id                                                          
247747   Abandoned in a park by their father, Amar, Akb...   43  
269880   In this fast-paced actioner, two Miami narcoti...   25  
281550   The plane crash that killed Buddy Holly also t...   33  
284890   A naïve young man and a rich city girl fall in...   25  
292118   After realizing that their boob tube is gone, ...   24

## Removing Rows & Columns

Finally, you can also remove columns or rows from your dataset. In order to drop rows and columns from a DataFrame, we can use function `drop`. Here's how you drop a row:

In [95]:
# This drops the row with index 247747. This is the same than doing drop(247747,axis=0)
movies.drop(labels=247747)

type                                   title           director  \
show_id                                                                        
269880      Movie                                Bad Boys        Michael Bay   
281550      Movie                                La Bamba        Luis Valdez   
284890      Movie                                 Barsaat  Rajkumar Santoshi   
292118      Movie         Beavis and Butt-head Do America         Mike Judge   
296682      Movie                                   Benji           Joe Camp   
...           ...                                     ...                ...   
81224868  TV Show                            Robot Trains                NaN   
81227195    Movie  Kalushi: The Story of Solomon Mahlangu        Mandla Dube   
81228864    Movie                         Blitz Patrollie     Andrew Wessels   
81235603  TV Show                        Sym-Bionic Titan                NaN   
81235729    Movie                                 Jezebel       Numa Perrier   

                                                       cast        country  \
show_id                                                                      
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890    Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   
296682    Benji, Deborah Walley, Peter Breck, Edgar Buch...  United States   
...                                                     ...            ...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...    South Korea   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   South Africa   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   South Africa   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...  United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                  date_added  release_year rating   duration  \
show_id                                                        
269880       October 1, 2019          1995      R    119 min   
281550       January 1, 2020          1987  PG-13    109 min   
284890         April 1, 2018          1995  TV-PG    166 min   
292118     November 20, 2019          1996  PG-13     81 min   
296682         March 6, 2018          1974      G     86 min   
...                      ...           ...    ...        ...   
81224868   December 31, 2019          2018  TV-Y7  2 Seasons   
81227195   November 29, 2019          2016  TV-MA    107 min   
81228864   December 27, 2019          2013  TV-MA    102 min   
81235603   December 15, 2019          2010  TV-PG   1 Season   
81235729    January 16, 2020          2019  TV-MA     86 min   

                         listed_in  \
show_id                              
269880          Action & Adventure   
281550              Classic Movies   
284890          Action & Adventure   
292118                    Comedies   
296682    Children & Family Movies   
...                            ...   
81224868                  Kids' TV   
81227195                    Dramas   
81228864        Action & Adventure   
81235603                  Kids' TV   
81235729                    Dramas   

                                                description  
show_id                                                      
269880    In this fast-paced actioner, two Miami narcoti...  
281550    The plane crash that killed Buddy Holly also t...  
284890    A naïve young man and a rich city girl fall in...  
292118    After realizing that their boob tube is gone, ...  
296682    After lovable abandoned mutt Benji is adopted ...  
...                                                     ...  
81224868  Keeping peace and safety in Train World is no ...  
81227195  The life and times of iconic South African lib...  
81228864 

In order to drop a column, we do the following:

In [96]:
# This drops column description. This is the same than doing drop('description',axis=1)
movies.drop(columns='description')

type                                   title           director  \
show_id                                                                        
247747      Movie                      Amar Akbar Anthony     Manmohan Desai   
269880      Movie                                Bad Boys        Michael Bay   
281550      Movie                                La Bamba        Luis Valdez   
284890      Movie                                 Barsaat  Rajkumar Santoshi   
292118      Movie         Beavis and Butt-head Do America         Mike Judge   
...           ...                                     ...                ...   
81224868  TV Show                            Robot Trains                NaN   
81227195    Movie  Kalushi: The Story of Solomon Mahlangu        Mandla Dube   
81228864    Movie                         Blitz Patrollie     Andrew Wessels   
81235603  TV Show                        Sym-Bionic Titan                NaN   
81235729    Movie                                 Jezebel       Numa Perrier   

                                                       cast        country  \
show_id                                                                      
247747    Vinod Khanna, Rishi Kapoor, Amitabh Bachchan, ...          India   
269880    Will Smith, Martin Lawrence, Téa Leoni, Tchéky...  United States   
281550    Lou Diamond Phillips, Esai Morales, Rosanna De...  United States   
284890    Twinkle Khanna, Bobby Deol, Danny Denzongpa, R...          India   
292118    Mike Judge, Bruce Willis, Demi Moore, Cloris L...  United States   
...                                                     ...            ...   
81224868  Bill Rogers, Carrie Savage, Ken Spassione, Ang...    South Korea   
81227195  Thabo Rametsi, Thabo Malema, Welile Nzuza, Jaf...   South Africa   
81228864  Joey Rasdien, David Kau, David Kibuuka, Chris ...   South Africa   
81235603  Tara Strong, Kevin Thoms, Brian Posehn, John D...  United States   
81235729  Tiffany Tenille, Numa Perrier, Stephen Barring...  United States   

                  date_added  release_year rating   duration  \
show_id                                                        
247747     December 31, 2019          1977  TV-14    172 min   
269880       October 1, 2019          1995      R    119 min   
281550       January 1, 2020          1987  PG-13    109 min   
284890         April 1, 2018          1995  TV-PG    166 min   
292118     November 20, 2019          1996  PG-13     81 min   
...                      ...           ...    ...        ...   
81224868   December 31, 2019          2018  TV-Y7  2 Seasons   
81227195   November 29, 2019          2016  TV-MA    107 min   
81228864   December 27, 2019          2013  TV-MA    102 min   
81235603   December 15, 2019          2010  TV-PG   1 Season   
81235729    January 16, 2020          2019  TV-MA     86 min   

                   listed_in  
show_id                       
247747    Action & Adventure  
269880    Action & Adventure  
281550        Classic Movies  
284890    Action & Adventure  
292118              Comedies  
...                      ...  
81224868            Kids' TV  
81227195              Dramas  
81228864  Action & Adventure  
81235603            Kids' TV  
81235729              Dramas  

[6234 rows x 10 columns]

---